repos:
-   repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
    - id: black
      exclude: ^.github/
      language_version: python3.10
      stages: [commit]
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      exclude: ^.github/
      stages: [commit]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: detect-private-key
-   repo: local
    hooks:
      - id: unittests
        name: run unit tests
        entry: coverage run -m unittest
        language: system
        pass_filenames: false
        args: ["discover"]
-   repo: https://github.com/radix-ai/auto-smart-commit
    rev: v1.0.2
    hooks:
      - id: auto-smart-commit
