name: Deploy Master
run-name: ${{ github.actor }} Deploy Master
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Version tagger
        id: version
        uses: juliansangillo/tag-version@v1
        with:
          production-branch: master
