name: Test Application
run-name: ${{ github.actor }} testing app
on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=B,C,E,F,W,T4,B9 --max-line-length=120 --max-complexity=18 --statistics
    - name: Test with unittest
      env:
        SECRET_KEY: ${{ vars.SECRET_KEY }}
        ALGORITHM: ${{ vars.ALGORITHM }}
        ACCESS_TOKEN_EXPIRE_MINUTES: ${{ vars.ACCESS_TOKEN_EXPIRE_MINUTES }}
        HOST_DB: ${{ vars.HOST_DB }}
        USER_DB: ${{ vars.USER_DB }}
        PASSWORD_DB: ${{ vars.PASSWORD_DB }}
      run: |
        coverage run -m unittest discover
    - name: Generate xml Coverage
      run: |
        coverage xml
    - name: Python Coverage
      if: ! contains(github.event.pull_request.user.login, 'dependabot[bot]')
      uses: orgoro/coverage@v3
      with:
        coverageFile: coverage.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        thresholdAll: 0.90
        thresholdNew: 0.95