on: 
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REGISTRY: docker.io

jobs:

  release-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ env.REGISTRY }}"
          echo "Got release version ${{ secrets.API_TOKEN }}"
